package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/fatih/color"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/d0cd/dispatcher/internal/adapter"
	"github.com/d0cd/dispatcher/internal/types"
	"github.com/d0cd/dispatcher/internal/workload"
)

var initFlags struct {
	force bool
}

var initCmd = &cobra.Command{
	Use:   "init [path]",
	Short: "Initialize Dispatcher configuration",
	Long:  "Inspects the workload and creates a dispatcher.yaml configuration file.",
	Args:  cobra.MaximumNArgs(1),
	RunE:  runInit,
}

func init() {
	initCmd.Flags().BoolVarP(&initFlags.force, "force", "f", false, "overwrite existing dispatcher.yaml")
}

func runInit(cmd *cobra.Command, args []string) error {
	path := "."
	if len(args) > 0 {
		path = args[0]
	}
	absPath, err := filepath.Abs(path)
	if err != nil {
		return fmt.Errorf("invalid path: %w", err)
	}

	outPath := filepath.Join(absPath, "dispatcher.yaml")
	if !initFlags.force {
		if _, err := os.Stat(outPath); err == nil {
			return fmt.Errorf("dispatcher.yaml already exists (use --force to overwrite)")
		}
	}

	bold := color.New(color.Bold)
	dim := color.New(color.Faint)

	bold.Fprintln(os.Stderr, "Inspecting workload...")

	spec, err := workload.InspectCodebase(absPath)
	if err != nil {
		return fmt.Errorf("inspection failed: %w", err)
	}

	// Build config from inspection using the shared type
	cfg := workload.DispatcherConfig{
		Name: spec.Name,
	}

	if spec.Package.Dockerfile != "" {
		dim.Fprintf(os.Stderr, "  Found %s\n", spec.Package.Dockerfile)
	} else if spec.Package.BaseImage != "" {
		dim.Fprintf(os.Stderr, "  Runtime: %s (will use %s)\n", spec.Runtime, spec.Package.BaseImage)
	}

	if len(spec.Entrypoints) > 0 {
		ep := pickEntrypoint(spec)
		if ep != "" {
			cfg.Command = adapter.RuntimeCommand(spec.Runtime, ep, false)
			dim.Fprintf(os.Stderr, "  Entrypoint: %s\n", ep)
		}
	}

	if spec.Requirements.GPU.Required {
		cfg.GPU = &workload.DispatchGPUConfig{
			Count:     spec.Requirements.GPU.Count,
			Model:     spec.Requirements.GPU.Model,
			Framework: spec.Requirements.GPU.Framework,
		}
		dim.Fprintf(os.Stderr, "  GPU: %d x %s\n", spec.Requirements.GPU.Count, spec.Requirements.GPU.Framework)
	}

	if len(spec.Ports) > 0 {
		cfg.Service = &workload.DispatchService{Port: spec.Ports[0]}
		dim.Fprintf(os.Stderr, "  Service port: %d\n", spec.Ports[0])
	}

	switch spec.DetectedKind {
	case types.WorkloadKindSandbox:
		cfg.Sandbox = true
	case types.WorkloadKindService:
		cfg.MaxCost = 20
	default:
		cfg.MaxCost = 5
	}

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("cannot generate config: %w", err)
	}

	// Header + commented examples of optional fields the scaffolder doesn't
	// populate. Users discover features (artifact retrieval, watchdog TTL,
	// retry classification) by reading the file they just generated rather
	// than hunting through docs.
	header := `# Dispatcher configuration
# Generated by 'dispatcher init'
# See https://github.com/d0cd/dispatcher for docs

# Optional fields you can add:
#
# outputs:
#   - results/         # workload-relative paths to rsync back before VM teardown
#   - model.bin        # use this to preserve crash dumps, results, partial outputs
#
# watchdogTtl: 30m     # how long a cloud VM lives after dispatcher stops heartbeating
#                      # (lower = smaller worst-case bill if dispatcher dies)
#
# retryTransientFailures: true   # retry once when failure looks environmental
#                                # (OOM kill, signal) — does NOT retry workload bugs

`
	fullContent := header + string(data)

	if err := os.WriteFile(outPath, []byte(fullContent), 0o644); err != nil {
		return fmt.Errorf("cannot write dispatcher.yaml: %w", err)
	}

	fmt.Fprintln(os.Stderr)
	color.New(color.FgGreen).Fprintf(os.Stderr, "Created %s\n", outPath)
	dim.Fprintln(os.Stderr, "Edit the file to customize, then run: dispatcher plan .")

	return nil
}

func pickEntrypoint(spec types.WorkloadSpec) string {
	for _, ep := range spec.Entrypoints {
		lower := strings.ToLower(ep)
		if strings.HasPrefix(lower, "dockerfile") || strings.Contains(lower, "compose") {
			continue
		}
		return ep
	}
	return ""
}
